version: '3.3'

services:

  mongodb:
      image: mongo:latest
      container_name: mongodb_container
      restart: always
      environment:
        # MONGO_INITDB_ROOT_USERNAME: root
        # MONGO_INITDB_ROOT_PASSWORD: rootpassword
        # MONGO_INITDB_USERNAME: admin
        # MONGO_INITDB_PASSWORD: adminpassword
        MONGO_INITDB_DATABASE: blogs-db
      volumes:
        - ./data/db:/data/db
      ports:
          - 27017:27017

  redis:
    image: redis:5.0
    ports: ["6379:6379"]
    restart: always
